# CI and PR triggers
pool:
  name: MY-WORK
  vmImage: 'darshan-wsl'

trigger: none

steps:

- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'TestHCL'
    applications: '429181b3-3ee7-4bf4-a163-315f9188691c'
    scanname: 'ufu'
    scantype: 'static'
    scanloc: '*'
    scanMethod: 'IRX'
    ScanSpeedOptions: 'thorough'