# CI and PR triggers
pool:
  name: MY-WORK
  vmImage: 'darshan-wsl'

trigger: none

steps:
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'HCL-APPSCAN'
    applications: '9de97e21-6ecc-468a-8fbc-770a8ca97fac'
    scanname: 'tsets'
    scantype: 'static'
    scanloc: '.'
    scanMethod: 'IRX'
    ScanSpeedOptions: 'thorough'
